# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_interval_sets_start <- function(x) {
    .Call(`_phinterval_cpp_interval_sets_start`, x)
}

cpp_interval_sets_starts <- function(x) {
    .Call(`_phinterval_cpp_interval_sets_starts`, x)
}

cpp_interval_sets_end <- function(x) {
    .Call(`_phinterval_cpp_interval_sets_end`, x)
}

cpp_interval_sets_ends <- function(x) {
    .Call(`_phinterval_cpp_interval_sets_ends`, x)
}

cpp_complement_interval_sets <- function(x) {
    .Call(`_phinterval_cpp_complement_interval_sets`, x)
}

cpp_invert_interval_sets <- function(x) {
    .Call(`_phinterval_cpp_invert_interval_sets`, x)
}

invert_interval_set <- function(x) {
    .Call(`_phinterval_invert_interval_set`, x)
}

cpp_setdiff_interval_sets <- function(x, y) {
    .Call(`_phinterval_cpp_setdiff_interval_sets`, x, y)
}

cpp_interval_sets_remove_instants <- function(x) {
    .Call(`_phinterval_cpp_interval_sets_remove_instants`, x)
}

cpp_intersect_interval_sets <- function(x, y) {
    .Call(`_phinterval_cpp_intersect_interval_sets`, x, y)
}

cpp_squash_lubridate_interval <- function(starts, spans, na_rm) {
    .Call(`_phinterval_cpp_squash_lubridate_interval`, starts, spans, na_rm)
}

cpp_lubridate_interval_to_interval_sets <- function(starts, spans) {
    .Call(`_phinterval_cpp_lubridate_interval_to_interval_sets`, starts, spans)
}

cpp_interval_sets_overlaps <- function(x, y) {
    .Call(`_phinterval_cpp_interval_sets_overlaps`, x, y)
}

cpp_squash_interval_set <- function(x) {
    .Call(`_phinterval_cpp_squash_interval_set`, x)
}

cpp_union_interval_sets <- function(x, y) {
    .Call(`_phinterval_cpp_union_interval_sets`, x, y)
}

cpp_interval_sets_within <- function(x, y) {
    .Call(`_phinterval_cpp_interval_sets_within`, x, y)
}

cpp_interval_sets_contains <- function(x, t) {
    .Call(`_phinterval_cpp_interval_sets_contains`, x, t)
}

