# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

as_phint_intvl_cpp <- function(starts, spans) {
    .Call(`_phinterval_as_phint_intvl_cpp`, starts, spans)
}

phint_phint_intersect_cpp <- function(x_size, x_starts, x_ends, y_size, y_starts, y_ends) {
    .Call(`_phinterval_phint_phint_intersect_cpp`, x_size, x_starts, x_ends, y_size, y_starts, y_ends)
}

phint_intvl_intersect_cpp <- function(x_size, x_starts, x_ends, y_starts, y_ends) {
    .Call(`_phinterval_phint_intvl_intersect_cpp`, x_size, x_starts, x_ends, y_starts, y_ends)
}

intvl_phint_intersect_cpp <- function(x_starts, x_ends, y_size, y_starts, y_ends) {
    .Call(`_phinterval_intvl_phint_intersect_cpp`, x_starts, x_ends, y_size, y_starts, y_ends)
}

intvl_intvl_intersect_cpp <- function(x_starts, x_ends, y_starts, y_ends) {
    .Call(`_phinterval_intvl_intvl_intersect_cpp`, x_starts, x_ends, y_starts, y_ends)
}

phint_squash_cpp <- function(starts, ends) {
    .Call(`_phinterval_phint_squash_cpp`, starts, ends)
}

intvl_squash_cpp <- function(starts, spans, na_rm) {
    .Call(`_phinterval_intvl_squash_cpp`, starts, spans, na_rm)
}

phint_squash_by_cpp <- function(size, starts, ends, group_locs, na_rm) {
    .Call(`_phinterval_phint_squash_by_cpp`, size, starts, ends, group_locs, na_rm)
}

