# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

phint_start_cpp <- function(size, starts, ends, tzone) {
    .Call(`_phinterval_phint_start_cpp`, size, starts, ends, tzone)
}

phint_end_cpp <- function(size, starts, ends, tzone) {
    .Call(`_phinterval_phint_end_cpp`, size, starts, ends, tzone)
}

intvl_start_cpp <- function(starts, spans, tzone) {
    .Call(`_phinterval_intvl_start_cpp`, starts, spans, tzone)
}

intvl_end_cpp <- function(starts, spans, tzone) {
    .Call(`_phinterval_intvl_end_cpp`, starts, spans, tzone)
}

phint_starts_cpp <- function(size, starts, ends, tzone) {
    .Call(`_phinterval_phint_starts_cpp`, size, starts, ends, tzone)
}

phint_ends_cpp <- function(size, starts, ends, tzone) {
    .Call(`_phinterval_phint_ends_cpp`, size, starts, ends, tzone)
}

phint_length_cpp <- function(size, starts, ends) {
    .Call(`_phinterval_phint_length_cpp`, size, starts, ends)
}

phint_lengths_cpp <- function(size, starts, ends) {
    .Call(`_phinterval_phint_lengths_cpp`, size, starts, ends)
}

as_phint_intvl_cpp <- function(starts, spans) {
    .Call(`_phinterval_as_phint_intvl_cpp`, starts, spans)
}

as_phint_datetime_cpp <- function(starts, ends) {
    .Call(`_phinterval_as_phint_datetime_cpp`, starts, ends)
}

phint_phint_intersect_cpp <- function(x_size, x_starts, x_ends, y_size, y_starts, y_ends) {
    .Call(`_phinterval_phint_phint_intersect_cpp`, x_size, x_starts, x_ends, y_size, y_starts, y_ends)
}

phint_intvl_intersect_cpp <- function(x_size, x_starts, x_ends, y_starts, y_ends) {
    .Call(`_phinterval_phint_intvl_intersect_cpp`, x_size, x_starts, x_ends, y_starts, y_ends)
}

intvl_phint_intersect_cpp <- function(x_starts, x_ends, y_size, y_starts, y_ends) {
    .Call(`_phinterval_intvl_phint_intersect_cpp`, x_starts, x_ends, y_size, y_starts, y_ends)
}

intvl_intvl_intersect_cpp <- function(x_starts, x_ends, y_starts, y_ends) {
    .Call(`_phinterval_intvl_intvl_intersect_cpp`, x_starts, x_ends, y_starts, y_ends)
}

phint_squash_cpp <- function(starts, ends) {
    .Call(`_phinterval_phint_squash_cpp`, starts, ends)
}

intvl_squash_cpp <- function(starts, spans, na_rm) {
    .Call(`_phinterval_intvl_squash_cpp`, starts, spans, na_rm)
}

datetime_squash_cpp <- function(starts, ends, na_rm) {
    .Call(`_phinterval_datetime_squash_cpp`, starts, ends, na_rm)
}

phint_squash_by_cpp <- function(size, starts, ends, group_locs, na_rm) {
    .Call(`_phinterval_phint_squash_by_cpp`, size, starts, ends, group_locs, na_rm)
}

intvl_squash_by_cpp <- function(starts, spans, group_locs, na_rm) {
    .Call(`_phinterval_intvl_squash_by_cpp`, starts, spans, group_locs, na_rm)
}

datetime_squash_by_cpp <- function(starts, ends, group_locs, na_rm) {
    .Call(`_phinterval_datetime_squash_by_cpp`, starts, ends, group_locs, na_rm)
}

tzone_is_valid_cpp <- function(tzone) {
    .Call(`_phinterval_tzone_is_valid_cpp`, tzone)
}

phint_unnest_cpp <- function(size, starts, ends, tzone, hole_to, keep_size) {
    .Call(`_phinterval_phint_unnest_cpp`, size, starts, ends, tzone, hole_to, keep_size)
}

intvl_unnest_cpp <- function(starts, spans, tzone, hole_to, keep_size) {
    .Call(`_phinterval_intvl_unnest_cpp`, starts, spans, tzone, hole_to, keep_size)
}

